resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/cb54482c7e3d45f6c1aac490dc937ed835de0333/snapshot.yaml

packages:
  - executable-spec
  - datil

flags:
  decentralized-updates:
    asserts: true
    pretty:  true

# Needed for weeder
# For this we need to upgrade to GHC >= 8.8
# ghc-options:
#   "$locals": -fwrite-ide-info

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3ac22a2fda11ca7131a011a9ea48fcbfdc26d6b3

  - git: https://github.com/input-output-hk/cardano-base
    commit: 0fcb3a306e96ce36fca75d62792c55ab1de871ea
    subdirs:
      - binary
      - cardano-crypto-class
      - slotting

  # Needed for lentil
  - terminal-progress-bar-0.4.1@sha256:ba857f3424ddb1034125163a9a384e9baab22e55de968259b046892c20ec0526,2257

  # Needed for the assertions library
  - monad-validate-1.2.0.0@sha256:9850f408431098b28806dd464b6825a88a0b56c84f380d7fe0454c1df9d6f881,3505
  - Unique-0.4.7.7@sha256:2269d3528271e25d34542e7c24a4e541e27ec33460e1ea00845da95b82eec6fa,2777

  # Needed for shrinking of products
  - git: https://github.com/nomeata/haskell-successors
    commit: 6f9f60eb3232b83cbffdc46301054c85983cf207

nix:
  shell-file: nix/stack-shell.nix
