resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/d673b92f2a2d9354d102514d0a0fa74f8248b14a/snapshot.yaml

packages:
  - executable-spec

extra-deps:
  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 52d8b21bf882353627fc23d1d0928ef671bac3af
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
  - tasty-hedgehog-1.0.0.1
  - bimap-0.4.0@sha256:d56712c094d40b4666e30d35fb0dad4058a2b753c5af4574f062237b2f7d5b67,1619

nix:
  shell-file: nix/stack-shell.nix
