resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/cb54482c7e3d45f6c1aac490dc937ed835de0333/snapshot.yaml

packages:
  - executable-spec
  - datil

flags:
  decentralized-updates:
    asserts: true
    pretty:  true

# Needed for weeder
# For this we need to upgrade to GHC >= 8.8
# ghc-options:
#   "$locals": -fwrite-ide-info

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3ac22a2fda11ca7131a011a9ea48fcbfdc26d6b3

  - git: https://github.com/input-output-hk/cardano-base
    commit: 0fcb3a306e96ce36fca75d62792c55ab1de871ea
    subdirs:
      - binary
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: c006b101b699b7b54a96d077fdbad07005b8da77
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec

  # Needed for cardano-ledger-specs
  - Unique-0.4.7.6

  # Needed for goblins, which is in turn needed for cardano-ledger-specs :(
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
  - moo-1.2
  - gray-code-0.3.1

  - tasty-hedgehog-1.0.0.1
  - bimap-0.4.0@sha256:d56712c094d40b4666e30d35fb0dad4058a2b753c5af4574f062237b2f7d5b67,1619
  - generic-monoid-0.1.0.0@sha256:00d1a7b7ff0890a3e3cba4032be24fe377c26e5e45d73afcacd42c98abb3b7e3,818
  # Needed for lentil
  - terminal-progress-bar-0.4.1@sha256:ba857f3424ddb1034125163a9a384e9baab22e55de968259b046892c20ec0526,2257

  # Needed for the assertions library
  - monad-validate-1.2.0.0@sha256:9850f408431098b28806dd464b6825a88a0b56c84f380d7fe0454c1df9d6f881,3505

nix:
  shell-file: nix/stack-shell.nix
