fc20-measurements.pdf: *.tex ../../working-document/figures
	latexmk -f -view=pdf fc20-measurements.tex

clean:
	rm -Rf latex.out
	rm -f *.aux *.log *.out *.cfg *.glo *.idx *.toc *.ilg *.ind *.lof *.lot *.bbl *.blg *.gls *.cut *.hd *.dvi *.ps *.thm *.rpi *.d *.fls *.pyc *.fdb_latexmk
